baseurl     = "https://hi2p-perim.github.io/hotsu/"
title       = "Hisanari Otsu"
copyright   = "&copy; 2026 Hisanari Otsu"
theme       = "academic-bootstrap"

[params]
  name               = "Hisanari Otsu"
  role               = "Assistant professor / Professeur adjoint"
  organization       = "Département d’informatique, Faculté des sciences, Université de Sherbrooke"
  organization_url   = "https://www.usherbrooke.ca/informatique/"
  address            = ""
  email              = "hisanari.otsu@usherbrooke.ca"
  linkedin           = "https://www.linkedin.com/in/hisanari-otsu"
  twitter            = "https://twitter.com/hisanari_otsu"
  googlescholar      = "https://scholar.google.com/citations?user=TdsG0_EAAAAJ"
  github             = "https://github.com/hi2p-perim"
  cv                 = "download/cv.pdf"
  role_2             = ""
  organization_2     = ""
  organization_url_2 = ""
  address_2          = ""
  email_2            = "hisanari.o@gmail.com"
  avatar             = "portrait.jpg"